services:
  mongodb:
    ports:
      - 27018:27017
    networks: 
      - api-network
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      timeout: 5s
      retries: 10
    
  patients.api:
    networks: 
      - api-network
    ports:
      - 5001:80
    image: patients.api
    build:
      context: .
      dockerfile: Patients.Api/Dockerfile
    environment:
      CONNECTION_STRING: 'mongodb://mongodb:27017'
      DATABASE_NAME: 'patients'
    depends_on: 
      mongodb:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost/health-check || exit 1
      interval: 3s
      timeout: 5s
      retries: 10

  patients.seed:
    networks: 
      - api-network
    image: patients.seed
    build:
      context: .
      dockerfile: Patients.Seed/Dockerfile
    environment:
      PATIENTS_API_URL: 'http://patients.api'
    depends_on: 
      patients.api:
        condition: service_healthy

networks:
  api-network: